import { StyleSheet } from 'react-native';
import { THEME } from './theme';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.COLOR.black,
    justifyContent: 'flex-start',
    padding: THEME.SPACING.lg,
  },
  box: {
    width: 100,
    height: 100,
  },
  title: {
    color: THEME.COLOR.white,
    fontSize: THEME.FONT_SIZE.xxxl,
    fontWeight: THEME.FONT_WEIGHT.black,
  },
  inputTitle: {
    color: THEME.COLOR.white,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.bold,
    marginTop: THEME.SPACING.xl,
    marginLeft: THEME.SPACING.sm,
    marginBottom: THEME.SPACING.sm,
  },
  input: {
    backgroundColor: THEME.COLOR.surface,
    color: THEME.COLOR.neutral400,
    padding: THEME.SPACING.md,
    borderRadius: THEME.BORDER_RADIUS.xl,
  },
  SubmitButton: {
    backgroundColor: THEME.COLOR.mint,
    paddingVertical: THEME.SPACING.md,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    shadowColor: '#0c4131',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
  },
  SubmitButtonText: {
    color: THEME.COLOR.black,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.black,
  },
  AddButton: {
    borderStyle: 'dashed',
    borderColor: THEME.COLOR.neutral500,
    borderWidth: 1,
    paddingVertical: THEME.SPACING.md,
    paddingHorizontal: THEME.SPACING.lg,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  AddButtonText: {
    color: THEME.COLOR.neutral500,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },
  logOutButton: {
    borderStyle: 'solid',
    borderColor: THEME.COLOR.neutral500,
    borderWidth: 1,
    backgroundColor: THEME.COLOR.surface,
    paddingVertical: THEME.SPACING.md,
    paddingHorizontal: THEME.SPACING.lg,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logOutButtonText: {
    color: THEME.COLOR.error,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },
  dateBar: {
    backgroundColor: THEME.COLOR.surface,
    borderRadius: THEME.BORDER_RADIUS.xl,
    justifyContent: 'center',
  },
  dateText: {
    color: THEME.COLOR.neutral400,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 110,
    backgroundColor: "#76E0BB",
    paddingHorizontal: 18,
    paddingVertical: 12,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    elevation: 8,
  },
  label: {
    fontSize: THEME.FONT_SIZE.xxl,
    color: "#000",
    fontWeight: "700",
  },
  mapContainer: {
    position: 'absolute',
    zIndex: 1,
    left: 15,
  },
  searchContainer: {
    position: 'absolute',
    top: 0,
    width: '100%',
    zIndex: 2,
  },
  searchContainer2: {
    position: 'absolute',
    top: 0,
    width: '100%',
    zIndex: 1,
  },
  textInputContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 25, // Sleek rounded pill design
    paddingHorizontal: 15,
    marginHorizontal: 15,
    marginTop: 65, // Spaced to clear the back button
    elevation: 5, // Android shadow
    shadowColor: '#000', // iOS shadow
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  textInput: {
    height: 50,
    color: '#000',
    fontSize: 16,
    backgroundColor: 'transparent',
  },
  listView: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 15,
    marginHorizontal: 15,
    marginTop: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  tripInfoCard: {
    position: 'absolute',
    bottom: 50,
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    alignItems: 'center',
  },
  timeText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#10b981',
  },
  distanceText: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '600',
    marginTop: 2,
  },
  routingPanelContainer: {
    position: 'absolute',
    top: 0,
    paddingTop: 60,
    width: '100%',
    zIndex: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingBottom: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  routingInputContainer: {
    borderRadius: 25,
    paddingHorizontal: 15,
    marginHorizontal: 15,
    marginTop: 10,
    backgroundColor: '#f3f4f6',
  },
  routingCloseButton: {
    position: 'absolute',
    top: 55,
    right: 20,
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderRadius: 15,
    padding: 5,
  },
  directionsButton: {
    position: 'absolute',
    bottom: 50,
    alignSelf: 'center',
    backgroundColor: THEME.COLOR.mint,
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 30,
    elevation: 8,
    shadowColor: '#0c4131',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  directionsButtonText: {
    color: THEME.COLOR.black,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.bold,
    marginLeft: 8,
  }
});
