import { StyleSheet } from 'react-native';
import { THEME } from './theme';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.COLOR.black,
    justifyContent: 'flex-start',
    padding: THEME.SPACING.lg,
  },
  box: {
    width: 100,
    height: 100,
  },
  title: {
    color: THEME.COLOR.white,
    fontSize: THEME.FONT_SIZE.xxxl,
    fontWeight: THEME.FONT_WEIGHT.black,
  },
  inputTitle: {
    color: THEME.COLOR.white,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.bold,
    marginTop: THEME.SPACING.xl,
    marginLeft: THEME.SPACING.sm,
    marginBottom: THEME.SPACING.sm,
  },
  input: {
    backgroundColor: THEME.COLOR.surface,
    color: THEME.COLOR.neutral400,
    padding: THEME.SPACING.md,
    borderRadius: THEME.BORDER_RADIUS.xl,
  },
  SubmitButton: {
    backgroundColor: THEME.COLOR.mint,
    paddingVertical: THEME.SPACING.md,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    shadowColor: '#0c4131',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
  },
  SubmitButtonText: {
    color: THEME.COLOR.black,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.black,
  },
  AddButton: {
    borderStyle: 'dashed',
    borderColor: THEME.COLOR.neutral500,
    borderWidth: 1,
    paddingVertical: THEME.SPACING.md,
    paddingHorizontal: THEME.SPACING.lg,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  AddButtonText: {
    color: THEME.COLOR.neutral500,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },
  logOutButton: {
    borderStyle: 'solid',
    borderColor: THEME.COLOR.neutral500,
    borderWidth: 1,
    backgroundColor: THEME.COLOR.surface,
    paddingVertical: THEME.SPACING.md,
    paddingHorizontal: THEME.SPACING.lg,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logOutButtonText: {
    color: THEME.COLOR.error,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },
  dateBar: {
    backgroundColor: THEME.COLOR.surface,
    borderRadius: THEME.BORDER_RADIUS.xl,
    justifyContent: 'center',
  },
  dateText: {
    color: THEME.COLOR.neutral400,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 110,
    backgroundColor: "#76E0BB",
    paddingHorizontal: 18,
    paddingVertical: 12,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    elevation: 8,
  },
  label: {
    fontSize: THEME.FONT_SIZE.xxl,
    color: "#000",
    fontWeight: "700",
  },
  mapContainer: {
    position: 'absolute',
    zIndex: 1,
    left: 15,
  },
});
