import { Dimensions, Platform, StyleSheet } from 'react-native';
import { THEME } from '../theme';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.COLOR.black,
    justifyContent: 'flex-start',
    padding: THEME.SPACING.lg,
  },
  title: {
    color: THEME.COLOR.white,
    fontSize: THEME.FONT_SIZE.xxxl,
    fontWeight: THEME.FONT_WEIGHT.black,
  },
  inputTitle: {
    color: THEME.COLOR.white,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.bold,
    marginTop: THEME.SPACING.xl,
    marginLeft: THEME.SPACING.sm,
    marginBottom: THEME.SPACING.sm,
  },
  input: {
    backgroundColor: THEME.COLOR.surface,
    color: THEME.COLOR.neutral400,
    padding: THEME.SPACING.md,
    borderRadius: THEME.BORDER_RADIUS.xl,
  },
  SubmitButton: {
    backgroundColor: THEME.COLOR.mint,
    paddingVertical: THEME.SPACING.md,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    shadowColor: '#0c4131',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
  },
  SubmitButtonText: {
    color: THEME.COLOR.black,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.black,
  },
  AddButton: {
    borderStyle: 'dashed',
    borderColor: THEME.COLOR.neutral500,
    borderWidth: 1,
    paddingVertical: THEME.SPACING.md,
    paddingHorizontal: THEME.SPACING.lg,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  AddButtonText: {
    color: THEME.COLOR.neutral500,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },
  TripButton: {
    borderStyle: 'solid',
    borderColor: THEME.COLOR.neutral500,
    backgroundColor: THEME.COLOR.surface,
    borderWidth: 1,
    paddingVertical: THEME.SPACING.md,
    paddingHorizontal: THEME.SPACING.lg,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
  },
  TripButtoneText: {
    color: THEME.COLOR.white,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },
  logOutButton: {
    borderStyle: 'solid',
    borderColor: THEME.COLOR.neutral500,
    borderWidth: 1,
    backgroundColor: THEME.COLOR.surface,
    paddingVertical: THEME.SPACING.md,
    paddingHorizontal: THEME.SPACING.lg,
    borderRadius: THEME.BORDER_RADIUS.xl,
    marginTop: THEME.SPACING.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logOutButtonText: {
    color: THEME.COLOR.error,
    fontSize: THEME.FONT_SIZE.lg,
    fontWeight: THEME.FONT_WEIGHT.medium,
  },

  // --- Shared map styles ---
  searchContainer: {
    position: 'absolute',
    top: 0,
    width: '100%',
    zIndex: 2,
  },
  locationButton: {
    position: 'absolute',
    bottom: 60,
    right: 16,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: THEME.COLOR.black,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
    elevation: 20,
  },
  backButtonContainer: {
    position: 'absolute',
    top: 65,
    left: Platform.select({
      ios: 25,
      android: 20,
    }),
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
    elevation: 8,
  },
  textInputContainer: {
    backgroundColor: THEME.COLOR.black,
    borderRadius: 25,
    paddingHorizontal: 15,
    marginHorizontal: 15,
    marginTop: 65,
    borderColor: THEME.COLOR.mint,
    borderWidth: 1,
    elevation: 5,
  },
  textInput: {
    height: 50,
    left: 30,
    color: THEME.COLOR.white,
    fontSize: 16,
    backgroundColor: 'transparent',
  },
  tripInfoCard: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: THEME.COLOR.black,
    paddingTop: 10,
    paddingHorizontal: 20,
    paddingBottom: 50,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(118, 224, 187, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 15,
  },
  tripInfoCardExpanded: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: Dimensions.get('window').height * 0.55,
    backgroundColor: THEME.COLOR.black,
    paddingTop: 10,
    paddingHorizontal: 20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(118, 224, 187, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 15,
  },
  timeText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#10b981',
  },
  distanceText: {
    fontSize: 14,
    color: '#9ca3af',
    fontWeight: '500',
    marginTop: 2,
  },
});
