import { StyleSheet } from "react-native";
import { THEME } from "../theme";

export const mapStyles = StyleSheet.create({
    mapContainer: {
        position: 'absolute',
        zIndex: 1,
        left: 15,
    },
    searchContainer: {
        position: 'absolute',
        top: 0,
        width: '100%',
        zIndex: 2,
    },
    searchContainer2: {
        position: 'absolute',
        top: 0,
        width: '100%',
        zIndex: 1,
    },
    textInputContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 25,
        paddingHorizontal: 15,
        marginHorizontal: 15,
        marginTop: 65,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    textInput: {
        height: 50,
        color: '#000',
        fontSize: 16,
        backgroundColor: 'transparent',
    },
    listView: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 15,
        marginHorizontal: 15,
        marginTop: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    tripInfoCard: {
        position: 'absolute',
        bottom: 50,
        alignSelf: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 30,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        alignItems: 'center',
    },
    timeText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#10b981',
    },
    distanceText: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '600',
        marginTop: 2,
    },
    routingPanelContainer: {
        position: 'absolute',
        top: 0,
        paddingTop: 60,
        width: '100%',
        zIndex: 2,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        paddingBottom: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 5,
    },
    routingInputContainer: {
        borderRadius: 25,
        paddingHorizontal: 15,
        marginHorizontal: 15,
        marginTop: 10,
        backgroundColor: '#f3f4f6',
    },
    routingCloseButton: {
        position: 'absolute',
        top: 55,
        right: 20,
        zIndex: 10,
        backgroundColor: 'rgba(0,0,0,0.1)',
        borderRadius: 15,
        padding: 5,
    },
    directionsButton: {
        position: 'absolute',
        bottom: 50,
        alignSelf: 'center',
        backgroundColor: THEME.COLOR.mint,
        paddingVertical: 15,
        paddingHorizontal: 40,
        borderRadius: 30,
        elevation: 8,
        shadowColor: '#0c4131',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        flexDirection: 'row',
        alignItems: 'center',
    },
    directionsButtonText: {
        color: THEME.COLOR.black,
        fontSize: THEME.FONT_SIZE.lg,
        fontWeight: THEME.FONT_WEIGHT.bold,
        marginLeft: 8,
    }
});