import { Dimensions, Platform, StyleSheet } from "react-native";
import { THEME } from "../theme";

export const mapStyles = StyleSheet.create({
    mapContainer: {
        position: 'absolute',
        zIndex: 1,
        left: 15,
    },
    searchContainer: {
        position: 'absolute',
        top: 0,
        width: '100%',
        zIndex: 2,
    },
    locationButton: {
        position: 'absolute',
        bottom: 60,
        right: 16,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: THEME.COLOR.black,
        justifyContent: 'center',
        alignItems: 'center',
    },
    directionsButton: {
        position: 'absolute',
        bottom: 140,
        right: 16,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: THEME.COLOR.mint,
        justifyContent: 'center',
        alignItems: 'center',
    },
    searchContainer2: {
        position: 'absolute',
        top: 0,
        width: '100%',
        zIndex: 1,
    },
    searchContainer2Focused: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        width: '100%',
        zIndex: 1,
    },
    backButtonContainer: {
        position: "absolute",
        top: 65,
        left: Platform.select({
            ios: 25,
            android: 20,
        }),
        width: 50,
        height: 50,
        justifyContent: "center",
        alignItems: "center",
        zIndex: 3,
        elevation: 8,
    },
    textInputContainer: {
        backgroundColor: THEME.COLOR.black,
        borderRadius: 25,
        paddingHorizontal: 15,
        marginHorizontal: 15,
        marginTop: 65,
        elevation: 5,
    },
    textInput: {
        height: 50,
        left: 30,
        color: THEME.COLOR.white,
        fontSize: 16,
        backgroundColor: 'transparent',
    },
    textInput2: {
        height: 50,
        color: THEME.COLOR.white,
        fontSize: 16,
        backgroundColor: 'transparent',
        flex: 1,
        width: '100%',
    },
    searchTextInset: {
        paddingRight: 24,
    },
    searchScreenTextInset: {
        paddingRight: 56,
    },
    searchClearButton: {
        position: 'absolute',
        right: 27,
        top: 80,
        zIndex: 10,
        elevation: 10,
    },
    listView: {
        backgroundColor: THEME.COLOR.black,
        borderRadius: 15,
        marginHorizontal: 15,
        marginTop: 10,
        elevation: 5,
    },
    listViewFocused: {
        backgroundColor: THEME.COLOR.black,
        flex: 1,
        maxHeight: Dimensions.get('window').height,
        marginHorizontal: 15,
        marginTop: 8,
        elevation: 5,
    },
    tripInfoCard: {
        position: 'absolute',
        bottom: 50,
        alignSelf: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 30,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        alignItems: 'center',
    },
    timeText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#10b981',
    },
    distanceText: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '600',
        marginTop: 2,
    },
    backButtonContainer2: {
        position: "absolute",
        top: Platform.select({
            ios: 70,
            android: 60,
        }),
        left: Platform.select({
            ios: 10,
            android: 5,
        }),
        width: 50,
        height: 50,
        justifyContent: "center",
        alignItems: "center",
        zIndex: 3,
        elevation: 8,
    },
    routingPanelContainer: {
        position: 'absolute',
        top: 0,
        width: '100%',
        zIndex: 2,
        backgroundColor: THEME.COLOR.black,
        paddingBottom: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 5,
    },
    routingInputContainer: {
        borderRadius: 25,
        marginLeft: 60,
        paddingHorizontal: 15,
        marginHorizontal: 15,
        marginTop: 10,
        backgroundColor: THEME.COLOR.black,
        borderWidth: 1,
        borderColor: THEME.COLOR.neutral500,
    },
    listViewDirections: {
        backgroundColor: THEME.COLOR.black,
        flex: 1,
        maxHeight: Dimensions.get('window').height,
        marginHorizontal: 15,
        marginTop: 8,
        elevation: 5,
    },
    routingCloseButton: {
        position: 'absolute',
        top: 55,
        right: 20,
        zIndex: 10,
        backgroundColor: 'rgba(0,0,0,0.1)',
        borderRadius: 15,
        padding: 5,
    },
});